### ISSUE TITLE
CATT Export not respected filtered state of data - only export what is currently 'active'

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vuetify#101]

**Comment by aaronlippold** [comment]
The data put in the PDF should be the active data displayed. So if I filter to the HIGH OPEN controls that is all that goes into the Excell

**Comment by ejaronne** [comment]
Seems to work fine for InSpec jsons, but when I try to CAAT export for a heim_tools output, it *only* works if some type of filtering is selected on the results. It won't download if the filtering is cleared.
