### ISSUE TITLE
Add `Help`, `About`, GitHub and Docs links to the upload modal to the landing page

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vuetify#149]
For users that do not yet have a results JSON yet, and need help getting started is blocked in our current workflow.

A simple Help and About Icon either in the side tabs or the lower right corner of the Upload Matrix.

**Comment by aaronlippold** [comment]
Suggested Workflow:

1. User hits the landing page
2. User clicks on Help, About or Docs icon in the footer
3. Upload modal closes and the new modal opens
4. When the user closes the Help, About or Docs Modal the Upload Modal reopens.

5. If the User selects the GitHub Link we open a new tab with the GitHub Page.

**Comment by aaronlippold** [comment]
Layouts:
  1. On lg, md - we can use icons and words
  2. On sm,xs - just use icons
  3. The tooltip should have the name of the action

**Comment by aaronlippold** [comment]
Please move this one level down so that the footer is outside the tab space.

**Comment by aaronlippold** [comment]
Also, we should use `flat` style buttons to drop the outline.

**Comment by aaronlippold** [comment]
<img width="1132" alt="Screen Shot 2019-11-01 at 10 15 41 AM" src="https://user-images.githubusercontent.com/1486440/68031978-1ab56b80-fc93-11e9-9f14-3d3d0e1d596d.png">

**Comment by aaronlippold** [comment]
<img width="699" alt="Screen Shot 2019-11-01 at 10 33 32 AM" src="https://user-images.githubusercontent.com/1486440/68032003-23a63d00-fc93-11e9-871e-024a6fa1a237.png">

**Comment by aaronlippold** [comment]
The bottom bar on all sizes should be as above with 'flat' buttons.

**Comment by aaronlippold** [comment]
* open Github and Doc in a new tab

**Comment by lukemalinowski** [comment]
* open in new tab
* right align

**Comment by aaronlippold** [comment]
Fixed
