### ISSUE TITLE
Please allow the file menu to open to the full width of the screen over top the other display items

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-vuetify#151]
Please triple the width of the file menu to allow reading of more of the filenames!

**Comment by aaronlippold** [comment]
I think a better solution might be just to have the full final name be visible via rollover or mouse over tool tip. Or there might be an auto scrolling capability that we allowed to scroll the file name. no matter how wide we make it eventually there will be some final name that's too wide so we should come up with a solution that just solves the root problem in my opinion

**Comment by ejaronne** [comment]
Please allow the file menu to open to the full width of the screen over top the other display items

**Comment by aaronlippold** [comment]
Fixed by #154
