### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall-vuetify#39]
* Majority of text in control details table should be bolded
* Need 4th dot for criticality
* Dots and criticality word should be seperated somehow
* Dots should be white, or default text color, not warning
* Colon should be dropped from control details header
* Blur out significantly more of landing modal background or move to new page again
* Replace v-file-input with pure button

**Comment by Mitriol** [comment]
Sidebar does not go full height!
