### ISSUE TITLE
Add version and release process for packaging

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vuetify#67]
We should establish as least a minimal release process for 1.0 which should include:

~8 Hours

**Suggestion**: Look at existing WebPack and NodeJS projects for processes we can reuse
**Suggestion**: Look into using _GitHub Actions_ and _Github Packages_

- [x] Running our Unit Tests
- [x] Linting and TS Validation
- [x] Tagging the code in GitHub
- [x] Updating the app version number according to SV2.0
- [x] Creating a 'CHANGELOG' file
- [x] Creating a 'VERSION' file
- [x] Creating a Release on GitHub Pages and Netlify

**Comment by aaronlippold** [comment]
I assigned everyone given that you all should talk about how we should go about this well

**Comment by aaronlippold** [comment]
* https://renatello.com/vuejs-app-version/ <== seems to be the best??
* https://medium.com/hceverything/how-to-show-your-app-version-from-package-json-in-your-vue-application-11e882b97d8c

**Comment by djhaynes** [comment]
Uses docs/ folder to deploy to Github Pages.
