### ISSUE TITLE
Make new landing page with file upload button

### ISSUE THREAD

**Issue by cjdoherty** [mitre/heimdall-vuetify#9]
Landing page should have a 'get started' upload file thing and a 'to know more about heimdall click here' type button.

**Comment by lukemalinowski** [comment]
Solution is to take jchenry's modal, and fill it in with Heimdall logo, primary activities, and escape hatches to other tools. Should have strong call to action on file upload, but keep in mind future releases will have to support linking to splunk and other alternate upload methods.

Other change is that modal should be triggered by the time you arrive at the page.

**Comment by aaronlippold** [comment]
Fixed #44
