### ISSUE TITLE
Incorrect return point on Failed Upload / Parsing - should return to App root.

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vuetify#94]
When you try to upload a 'broken' file the modal shows the issue - still too short a time - and should return you to the Upload Nexus modal 

At the moment it returns you to https://heimdall-vuetify.netlify.com/#/results/2. 

It should be https://heimdall-vuetify.netlify.com/ correct?

**Comment by Mitriol** [comment]
I got it - just need to push up the branch
